.TH ALTERNC-ADMINTOOLS 8 "november 24, 2003"

.SH NAME
alternc-admintools \- Admin tools for AlternC

.SH DESCRIPTION

AlternC Admin Tools are a set of litlle utilities that can help sys-admins in their day-life use of AlternC.
.PP

\fBalternc-admintools\fP is:
.sp 1
.IP 
top_http_users: apache basic stats
.br
top_mysql_users: mysql basic stats
.br
top_ftp_users: ftp basic stats
.br
get_domains_by_account: domains hosted by an account
.br
get_account_by_domain: account that host a domain
.br
get_mail_for_account: give inscription mail for an account

.SH SEE
.BR top_http_users (8),
.BR top_mysql_users (8),
.BR top_ftp_users (8),
.br
.BR get_domains_by_account (8),
.BR get_account_by_domain (8),
.BR get_mail_for_account (8)
