.TH ALTERNC.INSTALL 8

.SH NAME
alternc.install \- Installation script for AlternC

.SH DESCRIPTION

AlternC is a hosting control panel that automatically configure your services based on optimal mass-hosting parameters. alternc.install is a script that do this automatic configuration.
.PP
This script is automatically launched at the end of alternc's package installation. 
.PP
You can launch it again when you changed anything in the /etc/alternc/templates configuration files.


