.TH ALTERNC-ADMINTOOLS 8 "24 novembre 2003"

.SH NOM
alternc-admintools \- Outils pour faciliter la vie de l'administrateur AlternC

.SH DESCRIPTION

Cette page de manuel documente brièvement la collection d'outils
.B alternc-admintools
.PP

\fBalternc-admintools\fP est un ensemble d'utilitaires qui comprend :
.sp 1
.IP 
top_http_users : stats apache
.br
top_mysql_users : stats mysql
.br
top_ftp_users : stats ftp
.br
get_domains_by_account : domaines hébergés par un compte
.br
get_account_by_domain : compte hébergeant un domaine
.br
get_mail_for_account : donne le mail associé à un compte

.SH VOIR
.BR top_http_users (8),
.BR top_mysql_users (8),
.BR top_ftp_users (8),
.br
.BR get_domains_by_account (8),
.BR get_account_by_domain (8),
.BR get_mail_for_account (8)
