
DELETE FROM default_subdomains WHERE domain_type="WEBMAIL";

ALTER TABLE actions CHANGE `type` ̀ type` ENUM('CREATE_FILE','FIX_USER','CREATE_DIR','DELETE','MOVE','FIX_DIR','FIX_FILE','CHMOD') DEFAULT NULL;

