#!/bin/sh -e

# Check that AlternC is properly installed/configured
if [ -f /etc/alternc/local.sh ]
then
    exit 0
else
    # Source debconf library.
    . /usr/share/debconf/confmodule
    db_version 2.0
    db_title AlternC-Awstats
    db_fset alternc-awstats/errorinstall seen false
    db_input medium alternc-awstats/errorinstall
    db_go
    # il FAUT qu'AlternC soit proprement configuré pour installer awstats
    exit 1
fi

#DEBHELPER#
