#!/bin/sh -e

# Debian alternc prerm
# Benjamin Sonntag <benjamin@alternc.org>

case "$1" in
remove)
    # remove postfix from the sasl group (might not be user will though...)
    deluser --quiet postfix sasl || true

    . /etc/alternc/local.sh

    FQDN_LETTER="`echo $FQDN | sed -e 's/.*\.\([^\.]\)[^\.]*\.[^\.]*$/\1/'`"

    rm -rf /var/alternc/bureau/locales
    rmdir -p /var/alternc/bureau 2> /dev/null || true
    rm -f /var/alternc/dns/bureau
    rm -f /var/alternc/dns/$FQDN_LETTER/$FQDN
    rmdir -p /var/alternc/html/a/admin 2> /dev/null || true
    rmdir -p /var/alternc/html/r/root 2> /dev/null || true
    rm -f /var/alternc/apacheconf/override_php.conf
    ;;

upgrade)
    ;;

purge)
    find /var/alternc/bureau/locales -type f -name "alternc.mo" -exec rm {} \;
    find /var/alternc/bureau/locales -type f -name "alternc" -exec rm {} \;
    rm /var/alternc/bureau/class/local.php
    rm -f /var/alternc/apacheconf/bureau
    rm -f /var/alternc/apacheconf/$FQDN_LETTER/$FQDN
    ;;

failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

*)
    echo "postrm called with unknown argument '$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#
