<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-13 at 15:55:58.
 */
class m_adminTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var m_admin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new m_admin;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers m_admin::hook_menu
     * @todo   Implement testHook_menu().
     */
    public function testHook_menu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::stop_if_jobs_locked
     * @todo   Implement testStop_if_jobs_locked().
     */
    public function testStop_if_jobs_locked()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::get_uid_by_login
     * @todo   Implement testGet_uid_by_login().
     */
    public function testGet_uid_by_login()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::get_creator
     * @todo   Implement testGet_creator().
     */
    public function testGet_creator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::onesu
     * @todo   Implement testOnesu().
     */
    public function testOnesu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::get_list
     * @todo   Implement testGet_list().
     */
    public function testGet_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::mailallmembers
     * @todo   Implement testMailallmembers().
     */
    public function testMailallmembers()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::get_creator_list
     * @todo   Implement testGet_creator_list().
     */
    public function testGet_creator_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::checkcreator
     * @todo   Implement testCheckcreator().
     */
    public function testCheckcreator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::add_shared_domain
     * @todo   Implement testAdd_shared_domain().
     */
    public function testAdd_shared_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::add_mem
     * @todo   Implement testAdd_mem().
     */
    public function testAdd_mem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::hook_admin_add_member
     * @todo   Implement testHook_admin_add_member().
     */
    public function testHook_admin_add_member()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::update_mem
     * @todo   Implement testUpdate_mem().
     */
    public function testUpdate_mem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::lock_mem
     * @todo   Implement testLock_mem().
     */
    public function testLock_mem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::unlock_mem
     * @todo   Implement testUnlock_mem().
     */
    public function testUnlock_mem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::del_mem
     * @todo   Implement testDel_mem().
     */
    public function testDel_mem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::renew_mem
     * @todo   Implement testRenew_mem().
     */
    public function testRenew_mem()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::renew_update
     * @todo   Implement testRenew_update().
     */
    public function testRenew_update()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::renew_get_expiry
     * @todo   Implement testRenew_get_expiry().
     */
    public function testRenew_get_expiry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::renew_get_status
     * @todo   Implement testRenew_get_status().
     */
    public function testRenew_get_status()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::renew_get_expiring_accounts
     * @todo   Implement testRenew_get_expiring_accounts().
     */
    public function testRenew_get_expiring_accounts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::normal2su
     * @todo   Implement testNormal2su().
     */
    public function testNormal2su()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::su2normal
     * @todo   Implement testSu2normal().
     */
    public function testSu2normal()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::listtld
     * @todo   Implement testListtld().
     */
    public function testListtld()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::dom_list
     * @todo   Implement testDom_list().
     */
    public function testDom_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::checkalldom
     * @todo   Implement testCheckalldom().
     */
    public function testCheckalldom()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::dom_lock
     * @todo   Implement testDom_lock().
     */
    public function testDom_lock()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::gettld
     * @todo   Implement testGettld().
     */
    public function testGettld()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::selecttldmode
     * @todo   Implement testSelecttldmode().
     */
    public function testSelecttldmode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::deltld
     * @todo   Implement testDeltld().
     */
    public function testDeltld()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::addtld
     * @todo   Implement testAddtld().
     */
    public function testAddtld()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::edittld
     * @todo   Implement testEdittld().
     */
    public function testEdittld()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::getadmin
     * @todo   Implement testGetadmin().
     */
    public function testGetadmin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::listPasswordPolicies
     * @todo   Implement testListPasswordPolicies().
     */
    public function testListPasswordPolicies()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::editPolicy
     * @todo   Implement testEditPolicy().
     */
    public function testEditPolicy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::checkPolicy
     * @todo   Implement testCheckPolicy().
     */
    public function testCheckPolicy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_admin::hook_upnp_list
     * @todo   Implement testHook_upnp_list().
     */
    public function testHook_upnp_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
