<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-13 at 15:55:58.
 */
class m_authipTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var m_authip
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new m_authip;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @covers m_authip::list_ip_whitelist
     * @todo   Implement testList_ip_whitelist().
     */
    public function testList_ip_whitelist()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_authip::hook_menu
     * @todo   Implement testHook_menu().
     */
    public function testHook_menu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_authip::list_ip
     * @todo   Implement testList_ip().
     */
    public function testList_ip()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_authip::ip_delete
     * @todo   Implement testIp_delete().
     */
    public function testIp_delete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_authip::get_allowed
     * @todo   Implement testGet_allowed().
     */
    public function testGet_allowed()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_authip::is_wl
     * @todo   Implement testIs_wl().
     */
    public function testIs_wl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_authip::is_in_subnet
     * @todo   Implement testIs_in_subnet().
     */
    public function testIs_in_subnet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_authip::ip_save_whitelist
     * @todo   Implement testIp_save_whitelist().
     */
    public function testIp_save_whitelist()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_authip::ip_save
     * @todo   Implement testIp_save().
     */
    public function testIp_save()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_authip::alternc_del_member
     * @todo   Implement testAlternc_del_member().
     */
    public function testAlternc_del_member()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_authip::get_auth_class
     * @todo   Implement testGet_auth_class().
     */
    public function testGet_auth_class()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_authip::ip_affected_save
     * @todo   Implement testIp_affected_save().
     */
    public function testIp_affected_save()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_authip::ip_affected_delete
     * @todo   Implement testIp_affected_delete().
     */
    public function testIp_affected_delete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_authip::call_hooks
     * @todo   Implement testCall_hooks().
     */
    public function testCall_hooks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_authip::list_affected
     * @todo   Implement testList_affected().
     */
    public function testList_affected()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
