<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-13 at 15:55:58.
 */
class m_broTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var m_bro
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new m_bro;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers m_bro::hook_menu
     * @todo   Implement testHook_menu().
     */
    public function testHook_menu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::convertabsolute
     * @todo   Implement testConvertabsolute().
     */
    public function testConvertabsolute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::get_user_root
     * @todo   Implement testGet_user_root().
     */
    public function testGet_user_root()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::get_userid_root
     * @todo   Implement testGet_userid_root().
     */
    public function testGet_userid_root()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::filelist
     * @todo   Implement testFilelist().
     */
    public function testFilelist()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::GetPrefs
     * @todo   Implement testGetPrefs().
     */
    public function testGetPrefs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::SetPrefs
     * @todo   Implement testSetPrefs().
     */
    public function testSetPrefs()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::icon
     * @todo   Implement testIcon().
     */
    public function testIcon()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::mime
     * @todo   Implement testMime().
     */
    public function testMime()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::fsize
     * @todo   Implement testFsize().
     */
    public function testFsize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::dirsize
     * @todo   Implement testDirsize().
     */
    public function testDirsize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::CreateDir
     * @todo   Implement testCreateDir().
     */
    public function testCreateDir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::CreateFile
     * @todo   Implement testCreateFile().
     */
    public function testCreateFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::DeleteFile
     * @todo   Implement testDeleteFile().
     */
    public function testDeleteFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::RenameFile
     * @todo   Implement testRenameFile().
     */
    public function testRenameFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::MoveFile
     * @todo   Implement testMoveFile().
     */
    public function testMoveFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::ChangePermissions
     * @todo   Implement testChangePermissions().
     */
    public function testChangePermissions()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::UploadFile
     * @todo   Implement testUploadFile().
     */
    public function testUploadFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::ExtractFile
     * @todo   Implement testExtractFile().
     */
    public function testExtractFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::CopyFile
     * @todo   Implement testCopyFile().
     */
    public function testCopyFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::CopyOneFile
     * @todo   Implement testCopyOneFile().
     */
    public function testCopyOneFile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::PathList
     * @todo   Implement testPathList().
     */
    public function testPathList()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::content
     * @todo   Implement testContent().
     */
    public function testContent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::viewurl
     * @todo   Implement testViewurl().
     */
    public function testViewurl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::can_edit
     * @todo   Implement testCan_edit().
     */
    public function testCan_edit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::is_extractable
     * @todo   Implement testIs_extractable().
     */
    public function testIs_extractable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::is_sqlfile
     * @todo   Implement testIs_sqlfile().
     */
    public function testIs_sqlfile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::download_link
     * @todo   Implement testDownload_link().
     */
    public function testDownload_link()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::content_send
     * @todo   Implement testContent_send().
     */
    public function testContent_send()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::save
     * @todo   Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::DownloadZ
     * @todo   Implement testDownloadZ().
     */
    public function testDownloadZ()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::DownloadTGZ
     * @todo   Implement testDownloadTGZ().
     */
    public function testDownloadTGZ()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::DownloadTBZ
     * @todo   Implement testDownloadTBZ().
     */
    public function testDownloadTBZ()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::DownloadZIP
     * @todo   Implement testDownloadZIP().
     */
    public function testDownloadZIP()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::_sort_filelist_name
     * @todo   Implement test_sort_filelist_name().
     */
    public function test_sort_filelist_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::_delete
     * @todo   Implement test_delete().
     */
    public function test_delete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::alternc_export_conf
     * @todo   Implement testAlternc_export_conf().
     */
    public function testAlternc_export_conf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::alternc_export_data
     * @todo   Implement testAlternc_export_data().
     */
    public function testAlternc_export_data()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_bro::getMaxAllowedUploadSize
     * @todo   Implement testGetMaxAllowedUploadSize().
     */
    public function testGetMaxAllowedUploadSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
