<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-13 at 15:55:58.
 */
use PHPUnit\Framework\TestCase;

class m_domTest extends TestCase
{
    /**
     * @var m_dom
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new m_dom;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @covers m_dom::get_panel_url_list
     * @todo   Implement testGet_panel_url_list().
     */
    public function testGet_panel_url_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::get_sub_domain_id_and_member_by_name
     * @todo   Implement testGet_sub_domain_id_and_member_by_name().
     */
    public function testGet_sub_domain_id_and_member_by_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::hook_menu
     * @todo   Implement testHook_menu().
     */
    public function testHook_menu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::domains_type_lst
     * @todo   Implement testDomains_type_lst().
     */
    public function testDomains_type_lst()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::domains_type_enable_values
     * @todo   Implement testDomains_type_enable_values().
     */
    public function testDomains_type_enable_values()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::domains_type_target_values
     * @todo   Implement testDomains_type_target_values().
     */
    public function testDomains_type_target_values()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::import_manual_dns_zone
     * @todo   Implement testImport_manual_dns_zone().
     */
    public function testImport_manual_dns_zone()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::import_manual_dns_entry
     * @todo   Implement testImport_manual_dns_entry().
     */
    public function testImport_manual_dns_entry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::is_it_a_redirect
     * @todo   Implement testIs_it_a_redirect().
     */
    public function testIs_it_a_redirect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::domains_type_regenerate
     * @todo   Implement testDomains_type_regenerate().
     */
    public function testDomains_type_regenerate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::domains_type_get
     * @todo   Implement testDomains_type_get().
     */
    public function testDomains_type_get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::domains_type_del
     * @todo   Implement testDomains_type_del().
     */
    public function testDomains_type_del()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::domains_type_update
     * @todo   Implement testDomains_type_update().
     */
    public function testDomains_type_update()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::sub_domain_change_status
     * @todo   Implement testSub_domain_change_status().
     */
    public function testSub_domain_change_status()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::enum_domains
     * @todo   Implement testEnum_domains().
     */
    public function testEnum_domains()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::del_domain_cancel
     * @todo   Implement testDel_domain_cancel().
     */
    public function testDel_domain_cancel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::del_domain
     * @todo   Implement testDel_domain().
     */
    public function testDel_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::domshort
     * @todo   Implement testDomshort().
     */
    public function testDomshort()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::add_domain
     * @todo   Implement testAdd_domain().
     */
    public function testAdd_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::create_default_subdomains
     * @todo   Implement testCreate_default_subdomains().
     */
    public function testCreate_default_subdomains()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::domdefaultdir
     * @todo   Implement testDomdefaultdir().
     */
    public function testDomdefaultdir()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::dump_axfr
     * @todo   Implement testDump_axfr().
     */
    public function testDump_axfr()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::lst_default_subdomains
     * @todo   Implement testLst_default_subdomains().
     */
    public function testLst_default_subdomains()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::update_default_subdomains
     * @todo   Implement testUpdate_default_subdomains().
     */
    public function testUpdate_default_subdomains()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::update_one_default
     * @todo   Implement testUpdate_one_default().
     */
    public function testUpdate_one_default()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::del_default_type
     * @todo   Implement testDel_default_type().
     */
    public function testDel_default_type()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::whois
     * @todo   Implement testWhois().
     */
    public function testWhois()
    {
        // Remove the following lines when you implement this test.
        $ns = $this->object->whois('alternc.org');
        sort($ns);
        $expected_ns = array(
            'primary.heberge.info',
            'secondary.heberge.info',
        );
        $this->assertSame($ns, $expected_ns);
    }

    /**
     * @covers m_dom::checkmx
     * @todo   Implement testCheckmx().
     */
    public function testCheckmx()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::get_domain_all
     * @todo   Implement testGet_domain_all().
     */
    public function testGet_domain_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::get_sub_domain_all
     * @todo   Implement testGet_sub_domain_all().
     */
    public function testGet_sub_domain_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::check_type_value
     * @todo   Implement testCheck_type_value().
     */
    public function testCheck_type_value()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::can_create_subdomain
     * @todo   Implement testCan_create_subdomain().
     */
    public function testCan_create_subdomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::set_sub_domain
     * @todo   Implement testSet_sub_domain().
     */
    public function testSet_sub_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::del_sub_domain
     * @todo   Implement testDel_sub_domain().
     */
    public function testDel_sub_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::set_ttl
     * @todo   Implement testSet_ttl().
     */
    public function testSet_ttl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::edit_domain
     * @todo   Implement testEdit_domain().
     */
    public function testEdit_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::enum_slave_ip
     * @todo   Implement testEnum_slave_ip().
     */
    public function testEnum_slave_ip()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::add_slave_ip
     * @todo   Implement testAdd_slave_ip().
     */
    public function testAdd_slave_ip()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::del_slave_ip
     * @todo   Implement testDel_slave_ip().
     */
    public function testDel_slave_ip()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::check_slave_account
     * @todo   Implement testCheck_slave_account().
     */
    public function testCheck_slave_account()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::echo_domain_list
     * @todo   Implement testEcho_domain_list().
     */
    public function testEcho_domain_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::get_domain_list
     * @todo   Implement testGet_domain_list().
     */
    public function testGet_domain_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::get_domain_all_summary
     * @todo   Implement testGet_domain_all_summary().
     */
    public function testGet_domain_all_summary()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::get_domain_byid
     * @todo   Implement testGet_domain_byid().
     */
    public function testGet_domain_byid()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::get_domain_byname
     * @todo   Implement testGet_domain_byname().
     */
    public function testGet_domain_byname()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::count_domains_all
     * @todo   Implement testCount_domains_all().
     */
    public function testCount_domains_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::enum_slave_account
     * @todo   Implement testEnum_slave_account().
     */
    public function testEnum_slave_account()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::add_slave_account
     * @todo   Implement testAdd_slave_account().
     */
    public function testAdd_slave_account()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::del_slave_account
     * @todo   Implement testDel_slave_account().
     */
    public function testDel_slave_account()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::lock
     * @todo   Implement testLock().
     */
    public function testLock()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::unlock
     * @todo   Implement testUnlock().
     */
    public function testUnlock()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::hook_dom_add_mx_domain
     * @todo   Implement testHook_dom_add_mx_domain().
     */
    public function testHook_dom_add_mx_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::hook_admin_del_member
     * @todo   Implement testHook_admin_del_member().
     */
    public function testHook_admin_del_member()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::hook_quota_get
     * @todo   Implement testHook_quota_get().
     */
    public function testHook_quota_get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::alternc_export_conf
     * @todo   Implement testAlternc_export_conf().
     */
    public function testAlternc_export_conf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }


    /**
     * @covers m_dom::get_problems
     * @todo   Implement testGet_problems().
     */
    public function testGet_problems()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_dom::default_domain_type
     * @todo   Implement testDefault_domain_type().
     */
    public function testDefault_domain_type()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
