<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-13 at 15:55:58.
 */
class m_mailTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var m_mail
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new m_mail;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers m_mail::hook_menu
     * @todo   Implement testHook_menu().
     */
    public function testHook_menu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::get_total_size_for_domain
     * @todo   Implement testGet_total_size_for_domain().
     */
    public function testGet_total_size_for_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::catchall_getinfos
     * @todo   Implement testCatchall_getinfos().
     */
    public function testCatchall_getinfos()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::catchall_del
     * @todo   Implement testCatchall_del().
     */
    public function testCatchall_del()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::catchall_set
     * @todo   Implement testCatchall_set().
     */
    public function testCatchall_set()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::hook_quota_get
     * @todo   Implement testHook_quota_get().
     */
    public function testHook_quota_get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::alternc_password_policy
     * @todo   Implement testAlternc_password_policy().
     */
    public function testAlternc_password_policy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::enum_domains
     * @todo   Implement testEnum_domains().
     */
    public function testEnum_domains()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::available
     * @todo   Implement testAvailable().
     */
    public function testAvailable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::enum_domain_mails
     * @todo   Implement testEnum_domain_mails().
     */
    public function testEnum_domain_mails()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::hook_mail_get_details
     * @todo   Implement testHook_mail_get_details().
     */
    public function testHook_mail_get_details()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::create
     * @todo   Implement testCreate().
     */
    public function testCreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::get_details
     * @todo   Implement testGet_details().
     */
    public function testGet_details()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::is_it_my_mail
     * @todo   Implement testIs_it_my_mail().
     */
    public function testIs_it_my_mail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::hook_dom_del_mx_domain
     * @todo   Implement testHook_dom_del_mx_domain().
     */
    public function testHook_dom_del_mx_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::get_account_by_mail_id
     * @todo   Implement testGet_account_by_mail_id().
     */
    public function testGet_account_by_mail_id()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::undelete
     * @todo   Implement testUndelete().
     */
    public function testUndelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::set_passwd
     * @todo   Implement testSet_passwd().
     */
    public function testSet_passwd()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::enable
     * @todo   Implement testEnable().
     */
    public function testEnable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::disable
     * @todo   Implement testDisable().
     */
    public function testDisable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::set_details
     * @todo   Implement testSet_details().
     */
    public function testSet_details()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::add_wrapper
     * @todo   Implement testAdd_wrapper().
     */
    public function testAdd_wrapper()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::create_alias
     * @todo   Implement testCreate_alias().
     */
    public function testCreate_alias()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::del_wrapper
     * @todo   Implement testDel_wrapper().
     */
    public function testDel_wrapper()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::alternc_export_conf
     * @todo   Implement testAlternc_export_conf().
     */
    public function testAlternc_export_conf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::enum_slave_account
     * @todo   Implement testEnum_slave_account().
     */
    public function testEnum_slave_account()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::check_slave_account
     * @todo   Implement testCheck_slave_account().
     */
    public function testCheck_slave_account()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::echo_domain_list
     * @todo   Implement testEcho_domain_list().
     */
    public function testEcho_domain_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::add_slave_account
     * @todo   Implement testAdd_slave_account().
     */
    public function testAdd_slave_account()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::del_slave_account
     * @todo   Implement testDel_slave_account().
     */
    public function testDel_slave_account()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::hook_dom_add_slave_domain
     * @todo   Implement testHook_dom_add_slave_domain().
     */
    public function testHook_dom_add_slave_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::hook_dom_add_mx_domain
     * @todo   Implement testHook_dom_add_mx_domain().
     */
    public function testHook_dom_add_mx_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_mail::hook_upnp_list
     * @todo   Implement testHook_upnp_list().
     */
    public function testHook_upnp_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
