<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-13 at 15:55:59.
 */
class m_piwikTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var m_piwik
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new m_piwik;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers m_piwik::hook_menu
     * @todo   Implement testHook_menu().
     */
    public function testHook_menu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::hook_admin_del_member
     * @todo   Implement testHook_admin_del_member().
     */
    public function testHook_admin_del_member()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::hook_quota_get
     * @todo   Implement testHook_quota_get().
     */
    public function testHook_quota_get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::url
     * @todo   Implement testUrl().
     */
    public function testUrl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::user_add
     * @todo   Implement testUser_add().
     */
    public function testUser_add()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::user_edit
     * @todo   Implement testUser_edit().
     */
    public function testUser_edit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::get_site_access
     * @todo   Implement testGet_site_access().
     */
    public function testGet_site_access()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::get_users_access_from_site
     * @todo   Implement testGet_users_access_from_site().
     */
    public function testGet_users_access_from_site()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::get_user
     * @todo   Implement testGet_user().
     */
    public function testGet_user()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::get_alternc_users
     * @todo   Implement testGet_alternc_users().
     */
    public function testGet_alternc_users()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::user_delete
     * @todo   Implement testUser_delete().
     */
    public function testUser_delete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::users_list
     * @todo   Implement testUsers_list().
     */
    public function testUsers_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::user_checkremote
     * @todo   Implement testUser_checkremote().
     */
    public function testUser_checkremote()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::user_remoteauth
     * @todo   Implement testUser_remoteauth().
     */
    public function testUser_remoteauth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::user_access
     * @todo   Implement testUser_access().
     */
    public function testUser_access()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::site_list
     * @todo   Implement testSite_list().
     */
    public function testSite_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::site_js_tag
     * @todo   Implement testSite_js_tag().
     */
    public function testSite_js_tag()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::get_alternc_sites
     * @todo   Implement testGet_alternc_sites().
     */
    public function testGet_alternc_sites()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::get_site_list
     * @todo   Implement testGet_site_list().
     */
    public function testGet_site_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::site_add
     * @todo   Implement testSite_add().
     */
    public function testSite_add()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::site_delete
     * @todo   Implement testSite_delete().
     */
    public function testSite_delete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::site_set_user_right
     * @todo   Implement testSite_set_user_right().
     */
    public function testSite_set_user_right()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::site_alias_add
     * @todo   Implement testSite_alias_add().
     */
    public function testSite_alias_add()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::clean_user_name
     * @todo   Implement testClean_user_name().
     */
    public function testClean_user_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::dev
     * @todo   Implement testDev().
     */
    public function testDev()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::call_page
     * @todo   Implement testCall_page().
     */
    public function testCall_page()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_piwik::call_privileged_page
     * @todo   Implement testCall_privileged_page().
     */
    public function testCall_privileged_page()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
