<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-13 at 15:55:59.
 */
use PHPUnit\Framework\TestCase;

class m_quotaTest extends TestCase
{
    /**
     * @var m_quota
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp();
        $this->object = new m_quota;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        parent::tearDown();
    }

    /**
     * @covers m_quota::hook_menu
     * @todo   Implement testHook_menu().
     */
    public function testHook_menu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::cancreate
     * @todo   Implement testCancreate().
     */
    public function testCancreate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::qlist
     * @todo   Implement testQlist().
     */
    public function testQlist()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::synchronise_user_profile
     * @todo   Implement testSynchronise_user_profile().
     */
    public function testSynchronise_user_profile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::create_missing_quota_profile
     * @todo   Implement testCreate_missing_quota_profile().
     */
    public function testCreate_missing_quota_profile()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::getquota
     * @todo   Implement testGetquota().
     */
    public function testGetquota()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::setquota
     * @todo   Implement testSetquota().
     */
    public function testSetquota()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::delquotas
     * @todo   Implement testDelquotas().
     */
    public function testDelquotas()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::getdefaults
     * @todo   Implement testGetdefaults().
     */
    public function testGetdefaults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::setdefaults
     * @todo   Implement testSetdefaults().
     */
    public function testSetdefaults()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::addtype
     * @todo   Implement testAddtype().
     */
    public function testAddtype()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::listtype
     * @todo   Implement testListtype().
     */
    public function testListtype()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::deltype
     * @todo   Implement testDeltype().
     */
    public function testDeltype()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::addquotas
     * @todo   Implement testAddquotas().
     */
    public function testAddquotas()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::display_val
     * @todo   Implement testDisplay_val().
     */
    public function testDisplay_val()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::_get_sum_sql
     * @todo   Implement test_get_sum_sql().
     */
    public function test_get_sum_sql()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::_get_count_sql
     * @todo   Implement test_get_count_sql().
     */
    public function test_get_count_sql()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::_get_size_and_record_sql
     * @todo   Implement test_get_size_and_record_sql().
     */
    public function test_get_size_and_record_sql()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_web_sum_all
     * @todo   Implement testGet_size_web_sum_all().
     */
    public function testGet_size_web_sum_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_web_sum_user
     * @todo   Implement testGet_size_web_sum_user().
     */
    public function testGet_size_web_sum_user()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_mail_sum_all
     * @todo   Implement testGet_size_mail_sum_all().
     */
    public function testGet_size_mail_sum_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_mail_sum_domain
     * @todo   Implement testGet_size_mail_sum_domain().
     */
    public function testGet_size_mail_sum_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_mail_count_all
     * @todo   Implement testGet_size_mail_count_all().
     */
    public function testGet_size_mail_count_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_mail_count_domain
     * @todo   Implement testGet_size_mail_count_domain().
     */
    public function testGet_size_mail_count_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_mail_details_domain
     * @todo   Implement testGet_size_mail_details_domain().
     */
    public function testGet_size_mail_details_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_mailman_sum_all
     * @todo   Implement testGet_size_mailman_sum_all().
     */
    public function testGet_size_mailman_sum_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_mailman_sum_domain
     * @todo   Implement testGet_size_mailman_sum_domain().
     */
    public function testGet_size_mailman_sum_domain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_mailman_sum_user
     * @todo   Implement testGet_size_mailman_sum_user().
     */
    public function testGet_size_mailman_sum_user()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_mailman_count_all
     * @todo   Implement testGet_size_mailman_count_all().
     */
    public function testGet_size_mailman_count_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_mailman_count_user
     * @todo   Implement testGet_size_mailman_count_user().
     */
    public function testGet_size_mailman_count_user()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_mailman_details_user
     * @todo   Implement testGet_size_mailman_details_user().
     */
    public function testGet_size_mailman_details_user()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_db_sum_all
     * @todo   Implement testGet_size_db_sum_all().
     */
    public function testGet_size_db_sum_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_db_sum_user
     * @todo   Implement testGet_size_db_sum_user().
     */
    public function testGet_size_db_sum_user()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_db_count_all
     * @todo   Implement testGet_size_db_count_all().
     */
    public function testGet_size_db_count_all()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_db_count_user
     * @todo   Implement testGet_size_db_count_user().
     */
    public function testGet_size_db_count_user()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_db_details_user
     * @todo   Implement testGet_size_db_details_user().
     */
    public function testGet_size_db_details_user()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::get_size_unit
     * @todo   Implement testGet_size_unit().
     */
    public function testGet_size_unit()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::quota_displaybar
     * @todo   Implement testQuota_displaybar().
     */
    public function testQuota_displaybar()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::hook_admin_del_member
     * @todo   Implement testHook_admin_del_member().
     */
    public function testHook_admin_del_member()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::hook_admin_add_member
     * @todo   Implement testHook_admin_add_member().
     */
    public function testHook_admin_add_member()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_quota::alternc_export_conf
     * @todo   Implement testAlternc_export_conf().
     */
    public function testAlternc_export_conf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
