<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-13 at 15:55:59.
 */
class m_variablesTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var m_variables
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new m_variables;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers m_variables::variable_init
     * @todo   Implement testVariable_init().
     */
    public function testVariable_init()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_variables::get_impersonated
     * @todo   Implement testGet_impersonated().
     */
    public function testGet_impersonated()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_variables::variable_init_maybe
     * @todo   Implement testVariable_init_maybe().
     */
    public function testVariable_init_maybe()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_variables::variable_get
     * @todo   Implement testVariable_get().
     */
    public function testVariable_get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_variables::variable_update_or_create
     * @todo   Implement testVariable_update_or_create().
     */
    public function testVariable_update_or_create()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_variables::del
     * @todo   Implement testDel().
     */
    public function testDel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_variables::display_valueraw_html
     * @todo   Implement testDisplay_valueraw_html().
     */
    public function testDisplay_valueraw_html()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_variables::display_value_html
     * @todo   Implement testDisplay_value_html().
     */
    public function testDisplay_value_html()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_variables::variables_list_name
     * @todo   Implement testVariables_list_name().
     */
    public function testVariables_list_name()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers m_variables::variables_list
     * @todo   Implement testVariables_list().
     */
    public function testVariables_list()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
