#!/bin/bash

# Apply diffs to build for jessie

# DON'T COMMIT ANYTHING AFTER launching this
# reset your repos back to the serverside one!

# The patch files were generated by running
# export REV_NEW=ebb3471f04d49dd839237608bafc396e8b5090e5; export REV_OLD=d6d9be4c6a751279c9ad2a9b50aeb5d3ff1f91f9; \
# for i in `git diff --name-only $REV_NEW $REV_OLD` ; do BASE_NAME=`echo $i | rev | cut -d '/' -f 1 | rev` ; \
# git diff -p $REV_NEW $REV_OLD -- "$i" > jessie/$BASE_NAME ; done

DIR_NAME=`dirname $0`
cd "$DIR_NAME"/../

for i in `ls "$DIR_NAME"`; do
  patch -p1 < "$DIR_NAME/$i"
done
