#!/bin/bash

# Apply diffs to build for wheezy

# DON'T COMMIT ANYTHING AFTER launching this
# reset your repos back to the serverside one!

# The patch files were generated by running
# REV_NEW=ebb3471f04d49dd839237608bafc396e8b5090e5 REV_OLD=3ae6c0a5c2eecf864319dd42afbfc995baee9f68 \
# for i in `git diff --name-only $REV_NEW $REV_OLD` ; do BASE_NAME=`echo $i | rev | cut -d '/' -f 1 | rev` ; \
# git diff -p $REV_NEW $REV_OLD -- "$i" > jessie/$BASE_NAME ; done

DIR_NAME=`dirname $0`
cd "$DIR_NAME"/../

for i in `ls "$DIR_NAME"`; do
  patch -p1 < "$DIR_NAME/$i"
done
