#!/usr/bin/php
<?php

// Rebuild the bind configuration's file
// with the IP of the slave dns

$FLAGFILE="/run/alternc/refresh_slave";
$TPL="/etc/alternc/templates/bind/slaveip.conf";
$TARGET="/var/lib/alternc/bind/slaveip.conf";

if (!file_exists($FLAGFILE)) exit(0);

// Bootstrap
require_once("/usr/share/alternc/panel/class/config_nochk.php");

$db->query("SELECT ip,class FROM slaveip;");
$str="";
while ($db->next_record()) {
    $str.="    ".$db->Record["ip"]."/".$db->Record["class"].";\n";
}

file_put_contents($TARGET,  str_replace("//AUTO-SLAVES//",$str, file_get_contents($TPL) ) );

chown($TARGET,"root");
chgrp($TARGET,"bind");
chmod($TARGET,0640);

putenv("PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin");
passthru("rndc reconfig");

unlink($FLAGFILE);


